### ISSUE TITLE
Service Worker environment (such as Cloudflare Workers) support

### ISSUE THREAD

**Issue by woozyking** [deta/deta-javascript#40]
Although the SDK states to have browser support (thus in theory should work with a Worker environment), in real testing, there's a subtle inhibition caused by the reference of the Node.js `fs` module when attempting to use `deta` in Cloudflare Workers:

```shell
% wrangler publish  # Cloudflare Workers CLI
....
👀  ./node_modules/deta/dist/index.browser.js
Module not found: Error: Can't resolve 'fs' in './node_modules/deta/dist'
resolve 'fs' in './node_modules/deta/dist'
```

In order to circumvent the issue (without tinkering with otherwise convoluted webpack configs), I have adapted the deta HTTP APIs using the native Fetch API into a drop-in replacement package https://github.com/woozyking/deta-worker (WIP but also easily dropped once this official SDK supports Worker env properly).

Since this official SDK already uses `node-fetch` to bridge the API parity with native web/worker, I think it would be a simple matter of package config (I opted to only use Babel without other packaging utilities) to resolve the `fs` issue.

**Comment by abdelhai** [comment]
adding this to our next major release to do list. thanks!
