### ISSUE TITLE
get ip from user

### ISSUE THREAD

**Issue by zoutepopcorn** [deta/deta-javascript#59]
I made a simple example, using deta with express.

Now I want to get the ip address from the visitor. I tried some code, but I'm not able to get the ip.

When I run ```deta visor open``` I will also not see the ip of the visitor:
```
    'x-forwarded-for': '99.82.162.217',
    'x-forwarded-port': '443',
    'x-forwarded-proto': 'https',
    'x-real-ip': '99.82.162.217',
```
Is it possible to get it somehow?

**Comment by abdelhai** [comment]
hi @zoutepopcorn, the IP is not available in Micros due to technical limitations: https://docs.deta.sh/docs/micros/about/#important-notes (10)
