### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Jaasim2008** [deta/deta-javascript#62]
Hey, I installed the Library / Package and after using it for my Deta Base (which i like it alot), I get
`ERROR in ./node_modules/deta/dist/index.browser.js 571:58-89`
`Module not found: Error: Can't resolve 'fs' in '.../node_modules/deta/dist'`

Is there anyway to Fix this?
can I Ignore this Error Somehow?

**Comment by halfninja** [comment]
I get this when trying to import and use `deta` on a client-side Next.JS component (i.e. the browser SDK), so I can build as a static site. Why would the browser version be importing the Node `fs` module?
